services:
  nginx:
    image: 'nginx:stable-alpine'
    ports:
      - '81:80'
    volumes:
      - './src:/var/www/html'
      - './nginx-default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mysql
  mysql:
    image: 'mysql'
    restart: unless-stopped
    tty: true
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=gym_logs_db
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=homestead
      - MYSQL_ROOT_PASSWORD=secret
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/var/www/html'
    ports:
      - '9000:9000'
  composer:
    image: 'composer:latest'
    volumes:
      - './src:/var/www/html'
    working_dir: /var/www/html
  npm:
    image: 'node:20.11'
    volumes:
      - './src:/var/www/html'
    working_dir: /var/www/html
    entrypoint:
      - npm