services:
  nginx:
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - './src:/var/www/html'
      - './nginx-default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mysql
  mysql:
    image: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: gym_logs
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - '8080:8080'
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/var/www/html'
    ports:
      - '9000:9000'
  # composer:
  #   image: composer
  #   volumes:
  #     - './src:/var/www/html'
  #   working_dir: /var/www/html
  npm:
    image: node:alpine # use alpine version
    volumes:
      - './src:/var/www/html'
    working_dir: /var/www/html
    entrypoint:
      - npm